language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
script:
- grunt deploy
branches:
  only:
  - master
env:
  global:
  - secure: XvzxzTCMQECS6KatJSyhV+rikICUK3BSmR/yHkRgCjMdu2a/L6xYJ7+VyG/yuLXe4AluwP87EqdMEkQCrFyj5gzhtWCXHPn3wm2IxZwXbmxxFyYgyAIi9qGsJut8LyocmB17RtWedhME+S8YPor7d2zr0Wywzdx3hAp8h5AdgFU=
